# Q1

```{r}
HPDgrid <- function(prob,level=0.95){
  prob.sort=sort(prob,decreasing = T)
  M=min(which(cumsum(prob.sort)>=level))
  height=prob.sort[M]
  HPD.index=which(prob>=height)
  HPD.level=sum(prob[HPD.index])
  res=list(index=HPD.index, level=HPD.level)
  return(res)
}

a=1
b=1
x=17
n=22
theta=seq(0,1,length=1001)
ftheta=dbeta(theta,a+x,n-x+b)
prob=ftheta/sum(ftheta)
HPD=HPDgrid(prob,0.95)
HPD.grid=c(min(theta[HPD$index]),max(theta[HPD$index]))
HPD.grid
```

# Q2

$$
\alpha=3.0742, \beta=12.1053
$$
$$
\pi(\theta|x_1,\cdots,x_n)\sim Beta(5.0742,20.1053)
$$
```{r}
#(1)
a=3.0742
b=12.1053
a2=a+2
b2=b+8

#(2)
plot(theta, dbeta(theta,a,b),ylab='posterior',type='n')
lines(theta, dbeta(theta,a2,b2),lty=2)
lines(theta, dbeta(theta,a,b),lty=1)
#10개의 정보가 더해져 0.2에 더 몰리는 분포를 얻었다.

#(3)
theta=seq(0,1,length=1001)
ftheta=dbeta(theta,a2,b2)
prob=ftheta/sum(ftheta)
HPD=HPDgrid(prob,0.95)
HPD.grid=c(min(theta[HPD$index]),max(theta[HPD$index]))
HPD.grid

#(4)
HPDsample <- function(theta,level=0.95){
  N=length(theta)
  theta.sort=sort(theta)
  M=ceiling(N*level)
  nCI=N-M
  CI.width=rep(0,nCI)
  for(i in 1:nCI) CI.width[i]=theta.sort[i+M]-theta.sort[i]
  index=which.min(CI.width)
  HPD=c(theta.sort[index], theta.sort[index+M])
  return(HPD)
}
N=10000
theta1=rbeta(N,a,b)
theta2=rbeta(N,a2,b2)

eta1=log(theta1/(1-theta1))
eta2=log(theta2/(1-theta2))


HPD=HPDsample(eta2)

plot(density(eta1),type='l',main='')
lines(density(eta2))
abline(v=HPD,lty=2)
```

# Q3
$$
{\alpha \over \alpha+\beta}=0.4~~~~~~~{\alpha+1 \over \alpha+1+\beta}=0.45
$$
$$
\alpha=4.4~~\beta=6.6
$$
```{r}
#(2)
a=4.4
b=6.6
x=3
n=10
theta=seq(0,1,length=1001)
ftheta=dbeta(theta,a+x,n-x+b)
prob=ftheta/sum(ftheta)

plot(theta,prob)
#beta(7.4,13.6)

#(3)
m=10
z=c(0:10)
pred.z=gamma(m+1)/gamma(z+1)/gamma(m-z+1)*beta(a+z+x,b+n-x+m-z)/beta(a+x,b+n-x)
plot(z,pred.z,type = 'h')

#monte-carlo
m=10
N=10000
theta=rbeta(N,a+x,b+n-x)
pred.z=c(1:(m+a))*0
for(z in c(0:m)) pred.z[z+1]=mean(dbinom(z,m,theta))
z=rbinom(N,m,theta)
plot(table(z)/N)
```

# Q4
$$
\pi(\theta)=1~~f(x|\theta)=\theta^3(1-\theta)^9
$$
$$
\pi(\theta|x)\sim Beta(4,10)
$$
$$
P(X_{n+1}=1|x_1,\cdots,x_n)={4 \over 14}
$$

# Q5

## (1)
0

## (2)
0

## (3)
$$
\pi(\theta|x_1,\cdots,x_n)\sim Beta(0.1,11)
$$

$$
f(z|x_1,\cdots,x_n)= {20 \choose z}{Be(11.1,21-z)\over Be(0.1,11)}
$$
$$
P(z>=1|x_1,\cdots,x_n)=1-P(z=0|x_1,\cdots,x_n)
$$

```{r}
gamma(11.1)*gamma(21)/gamma(32.1)/(gamma(0.1)*gamma(11)/gamma(11.1))
#1-0.000000000128
```

# Q6
$$
\theta_1|x_1 \sim Beta(11,11)
$$
$$
\theta_2|x_2 \sim Beta(15,7)
$$
```{r}
a=1
b=1
n=20
x1=10
x2=14

theta1=rbeta(10000,a+x1,b+n-x1)
theta2=rbeta(10000,a+x2,b+n-x2)
xi=log((theta1/(1-theta1))/(theta2/(1-theta2)))
#로그 오즈비 추정치
mean(xi)
#로그 오즈비 표준오차
sd(xi)

HPD=HPDsample(xi)
HPD
par(family='AppleGothic')
plot(density(xi),type = 'l',xlab = '로그오즈비',main = '로그 오즈비의 사후 분포')
abline(v=HPD, lty=2)
```

