---
title: "베이지안 통계추론 5장 과제"
author: "응용통계학과 이준혁"
date: "2023-10-06"
output:
  html_document:
    css: styles.css
    #code_folding: show
    fig_caption: yes
    fig_height: 7.5
    fig_width: 10
    fig_retina: null
    highlight: haddock
    self_contained: yes
    theme: cosmo
    toc: yes
    toc_depth: 6
    toc_float: yes
    fig_dpi: 300
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<style type="text/css">
  body, td {
     font-size: 16px;
     font-family: 맑은 고딕
  }
  code.r{
    font-size: 16px;
    font-weight: bold;
    font-family: 맑은 고딕
  }
  pre {
    font-size: 14px
    font-family: 맑은 고딕
  }
  h1,h2,h3,h4,h5,h6{
    font-family: 맑은 고딕;
    font-weight: bold;
  }
  h1{
    font-size: 18pt;
  }
  h2{
    font-size: 16pt;
  }
  h3{
    font-size: 14pt;
  }
</style>

---
```{r}
library(ggplot2)
```

# 1번 문제

```{r}
HPDgrid <- function(prob,level=0.95){
  prob.sort=sort(prob,decreasing = T)
  M=min(which(cumsum(prob.sort)>=level))
  height=prob.sort[M]
  HPD.index=which(prob>=height)
  HPD.level=sum(prob[HPD.index])
  res=list(index=HPD.index, level=HPD.level)
  return(res)
}

a=1; b=1; x=17; n=22
theta=seq(0,1,length=10001)
ftheta=dbeta(theta,a+x,n-x+b)
prob=ftheta/sum(ftheta)
HPD=HPDgrid(prob,0.95)
HPD.grid=c(min(theta[HPD$index]),max(theta[HPD$index]))
HPD.grid
```

# 2번 문제

2-(1)
$$ \alpha=3.0742, \beta=12.1053 $$
$$ \pi(\theta|x_1,x_2,x_3,\cdots,x_n)\sim B(5.074,20.105) $$
```{r}
a=3.0742
b=12.1053
a2=a+2
b2=b+8

# 2-(2)
plot(theta, dbeta(theta,a,b), ylab='posterior',type='n')
lines(theta, dbeta(theta,a,b),lty=1)
lines(theta, dbeta(theta,a2,b2), lty=2)
# 0.2부근에 더 쏠리는 결과를 볼 수 있다.

# 2-(3)
theta=seq(0,1,length=10001)
ftheta=dbeta(theta,a2,b2)
prob=ftheta/sum(ftheta)
HPD=HPDgrid(prob,0.95)
HPD.grid=c(min(theta[HPD$index]),max(theta[HPD$index]))
HPD.grid

# 2-(4)
HPDsample <- function(theta,level=0.95){
  N=length(theta)
  theta.sort=sort(theta)
  M=ceiling(N*level)
  nCI=N-M
  CI.width=rep(0,nCI)
  for(i in 1:nCI) CI.width[i]=theta.sort[i+M]-theta.sort[i]
  index=which.min(CI.width)
  HPD=c(theta.sort[index], theta.sort[index+M])
  return(HPD)
}
N=10000
theta1=rbeta(N,a,b)
theta2=rbeta(N,a2,b2)

eta1 =log(theta1/(1-theta1))
eta2 =log(theta2/(1-theta2))


HPD=HPDsample(eta2)

plot(density(eta1),type='l',main='')
lines(density(eta2))
abline(v=HPD,lty=2)
```

# 3번 문제

3-(1)
$$ {\alpha \over \alpha+\beta}=0.4,{\alpha+1 \over \alpha+1+\beta}=0.45 $$
$$ \alpha=4.4, \beta=6.6 $$
```{r}
# 3-(2)
a=4.4;b=6.6;x=3;n=10
theta=seq(0,1,length=10001)
ftheta=dbeta(theta,a+x,n-x+b)
prob=ftheta/sum(ftheta)
plot(theta,prob)

# 3-(3)
m=10
z=c(0:10)
pred.z=gamma(m+1)/gamma(z+1)/gamma(m-z+1)*beta(a+z+x,b+n-x+m-z)/beta(a+x,b+n-x)
plot(z,pred.z,type = 'h')

#몬테카를로
m=10
N=10000
theta=rbeta(N,a+x,b+n-x)
pred.z=c(1:(m+a))*0
for(z in c(0:m)) pred.z[z+1]=mean(dbinom(z,m,theta))
z=rbinom(N,m,theta)
plot(table(z)/N)
```

