# Q1
```{r}
x <- c(105,109,126,92,101,108,102,118,99,90,86,102)
mean(x)
100/length(x)
#사후 N(103,8.33)

# 대립가설 102 이하일 확률
# P(theta<=102)
pnorm(102,103,sqrt(8.33))

# 귀무가설 102 이상일 확률
# P(theta>102)
1-pnorm(102,103,sqrt(8.33))
#0.62 > 0.5 이므로 귀무가설을 채택한다.
```

# Q2

```{r}
#사전 분포 Gamma(2,0.1)
#사후 분포 Gamma(218,10.1)

# (1)
# p0 = P(theta>20|x)
p0=1-pgamma(20,218,10.1)
p0

# (2)
# 사후비
# p0/p1
p0/(1-p0)

# pi0
pi0=1-pgamma(20,2,0.1)
pi0

# 사전비
# pi0/pi1
pi0/(1-pi0)

# 베이즈 상수
# 사후비/사전비
(p0/(1-p0))/(pi0/(1-pi0))

# (3)
# 새로운 사전비
p00=1-pgamma(20,15,1)
p00/(1-p00)
(p0/(1-p0))/(pi0/(1-pi0))*p00/(1-p00)
```

# Q3
```{r}
pi0=0.5
pi1=1-pi0
n=30
x=5
a=1
b=1

m1x=choose(30,5)*gamma(2)/(gamma(1)*gamma(1))*(gamma(6)*gamma(26))/gamma(32)

b01=((3/16)^5*(1-3/16)^25)/(gamma(2)/(gamma(1)*gamma(1))*(gamma(6)*gamma(26))/gamma(32))

# 사후비
b01*(0.5/0.5)
#H0를 채택
```

# Q4

```{r}
# (1)
#검정통계량
z=(0.25-0)/(1/10)
z

# p-value
1-pnorm(z)

# (2)
# H_0 사후확률
(0.5*(1/sqrt(2*pi)*exp(-0.25/2)))/(0.5*(1/sqrt(2*pi)*exp(-0.25/2))+0.5*(1/sqrt(2*pi*1.01)*exp(-0.25/(2*1.01))))

# H_1 사후확률
1-(0.5*(1/sqrt(2*pi)*exp(-0.25/2)))/(0.5*(1/sqrt(2*pi)*exp(-0.25/2))+0.5*(1/sqrt(2*pi*1.01)*exp(-0.25/(2*1.01))))

```

# Q5

```{r}
a=0.1
b=0.9
n=10
x=2

# (1)
# beta(2.1,8.9)
a1=2.1
b1=8.9
mu=a1/(a1+b1)
sig=sqrt(a1*b1/((a1+b1)^2*(a1+b1+1)))

# p0
p0=pnorm(0.1,mu,sig)
p0
# p1
p1=1-p0
p1
# 사후비
p0/p1

# 사전비
a2=0.1
b2=0.9
mu2=a2/(a2+b2)
sig2=sqrt(a2*b2/((a2+b2)^2*(a2+b2+1)))

pi0=pnorm(0.1,mu2,sig2)
pi0

pi0/(1-pi0)

# 베이즈 상수
(p0/p1)/(pi0/(1-pi0))


# (2)
# 베이즈 상수
(0.1^2*0.9^8)/(gamma(1) / (gamma(0.1) * gamma(0.9))  *  (gamma(2.1) * gamma(8.9)) / gamma(11))

# 사후비
# 베이즈상수 * 사전비
4.659373*(0.5/0.5)
```

