# Q1
```{r}
a=1/2
b=0
n=6
s=15
theta <- seq(0,6,length=100)
#gamma(15.5,6)
plot(theta,dgamma(theta,a+s,b+n),type='l')
```

# Q2
## (1)
```{r}
a=1
b=1
n=1
s=12
theta <- seq(0,20,length=1000)
plot(theta,dgamma(theta,a,b),type = 'l')
lines(theta,dgamma(theta,a+s,b+n),type = 'l')

# 사전평균 1
# 사후평균 (1+12)/(1+1)=6.5
```

## (2)
$$
\pi(\theta|x_1,\cdots,x_n)\sim gamma(9,2)
$$

$$
X_{n+1}|x_1,\cdots,x_n \sim NB(9,2/3)
$$
```{r}
pnbinom(9,9,2/3)-pnbinom(7,9,2/3)
```

# Q3
## (1)
```{r}
a=2
b=1
n=10
s=12

theta <- seq(0,6,length=100)
#gamma(14,11)
plot(theta,dgamma(theta,a+s,b+n),type='l')
```

## (2)
```{r}
HPDgrid <- function(prob,level=0.95){
  prob.sort=sort(prob,decreasing = T)
  M=min(which(cumsum(prob.sort)>=level))
  height=prob.sort[M]
  HPD.index=which(prob>=height)
  HPD.level=sum(prob[HPD.index])
  res=list(index=HPD.index, level=HPD.level)
  return(res)
}

a=2
b=1
n=10
s=12

theta <- seq(0,6,length=100)
ftheta <- dgamma(theta,a+s,b+n)
prob <- ftheta/sum(ftheta)
HPD <- HPDgrid(prob,0.95)
HPD.grid <- c(min(theta[HPD$index]),max(theta[HPD$index]))
HPD.grid

plot(theta,dgamma(theta,a+s,b+n),type='l')
abline(v=HPD.grid,lty=2)
```

## (3)
```{r}
HPDsample <- function(theta,level=0.95){
  N=length(theta)
  theta.sort=sort(theta)
  M=ceiling(N*level)
  nCI=N-M
  CI.width=rep(0,nCI)
  for(i in 1:nCI) CI.width[i]=theta.sort[i+M]-theta.sort[i]
  index=which.min(CI.width)
  HPD=c(theta.sort[index], theta.sort[index+M])
  return(HPD)
}

a=2
b=1
n=10
s=12

rtheta <- rgamma(10000,a+s,b+n)
eta <- log(rtheta)

HPD <- HPDsample(eta)
plot(density(eta))
abline(v=HPD)
```

# Q4
```{r}
a=1
b=1
n1=100
n2=100
s1=225
s2=210

sim=10000
theta1=rgamma(sim,a+s1,b+n1)
theta2=rgamma(sim,a+s2,b+n2)
eta=log(theta1/theta2)

mean(eta)

HPD=HPDsample(eta)

plot(density(eta),type='l')
abline(v=HPD,lty=2)
abline(v=mean(eta))

```

