---
title: "Welcome to Statistical Methods II: CDA"
author: "석사 2차 김통계/박응용"
date: "`r Sys.Date()`"
---


# 개요

 + R에서 모든 것은 `object(객체)`이다.

 + R에서 모든 것은 `function calls(함수 호출)`이다.


# R Code
```{r message=FALSE, warning=FALSE}
lre <- "#A50034"
lgr <- "#6b6b6b"
lgo <- "#FAB23D"

test <- read.csv(paste0("./data/recognition.test.csv"))

test <- test %>%
 mutate(id = fct_reorder(id, mean), 
        success_p = ppois(2, mean))
```

# Table

```{r echo=FALSE, message=FALSE, warning=FALSE}
table <- test %>% dplyr::select(id, mean, success_p)
knitr::kable(head(table))
```


# Plots
```{r echo=FALSE}
#| fig.width = 5, 
#| fig.asp =1.1,
#| fig.align = "center",
#| message = FALSE,
#| warning = FALSE
#| 
test %>% ggplot(aes(x = fct_reorder(id, -mean), 
                    y = mean)) +
 geom_bar(stat = "identity", 
          color = "white", fill = "red") + 
 labs(x = "인식 대상", y = "평균 결점") +
 coord_flip() +
 theme_bw() + 
 theme(axis.text.y = element_text(size = 5))
```

# Tabset {.tabset}

## Data 

```{r}
str(test)
```


## Plots
```{r echo=FALSE}
#| fig.width = 5, 
#| fig.asp =1.1,
#| fig.align = "center",
#| message = FALSE,
#| warning = FALSE
#| 
p1 <- test %>% ggplot(aes(x = fct_reorder(id, -mean), 
                    y = mean)) +
 geom_bar(stat = "identity", 
          color = "white", fill = "red") + 
 labs(x = "인식 대상", y = "평균 결점") +
 coord_flip() +
 theme_bw() + 
 theme(axis.text.y = element_text(size = 5))

p2 <- test %>% ggplot(aes(x = fct_reorder(id, success_p), 
                    y = success_p)) +
 geom_bar(stat = "identity", 
          color = "white", fill = "blue") + 
 geom_hline(yintercept = 0.05, color = "red") +
 geom_hline(yintercept = 0.10, color = "red") +
 labs(x = "인식 대상", y = "조건 만족 확률") +
 coord_flip() +
 theme_bw() + 
 theme(axis.text.y = element_text(size = 5))
(p1 | p2)
```

## Tables


```{r echo=FALSE, message=FALSE, warning=FALSE}

knitr::kable(head(table))
```


## Results

고려한 데이터의 `문자값 요약 결과`는 다음과 같다. 

```{r echo=FALSE}
summary(table)
```

# R Code 추출
```{r eval=FALSE, include=TRUE}
e_code("welcome.cda.rmd", "code.cda.r")
```


