---
title: "통계 방법론1"
author: "응용통계학과 이준혁"
date: "2023-09-23(토)"
output:
  html_document:
    css: styles.css
    #code_folding: show
    fig_caption: yes
    fig_height: 7.5
    fig_width: 10
    fig_retina: null
    highlight: haddock
    self_contained: yes
    theme: cosmo
    toc: yes
    toc_depth: 6
    toc_float: yes
    fig_dpi: 300
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<style type="text/css">
  body, td {
     font-size: 16px;
     font-family: 맑은 고딕
  }
  code.r{
    font-size: 16px;
    font-weight: bold;
    font-family: 맑은 고딕
  }
  pre {
    font-size: 14px
    font-family: 맑은 고딕
  }
  h1,h2,h3,h4,h5,h6{
    font-family: 맑은 고딕;
    font-weight: bold;
  }
  h1{
    font-size: 18pt;
  }
  h2{
    font-size: 16pt;
  }
  h3{
    font-size: 14pt;
  }
  table{
    font-size: 20px;
  }
</style>
<br><br><br><br>

---
```{r}
library(ggplot2)
library(gridExtra)
```

```{r}
# 1. Normal Population Distribution
set.seed(123)
population1 <- rnorm(100000, mean=100, sd=10)
sample_means1 <- replicate(1000, mean(sample(population1, size=30)))

p1 <- ggplot(data.frame(x=population1), aes(x)) + geom_density() + xlim(80, 120)
p2 <- ggplot(data.frame(x=sample_means1), aes(x)) + geom_histogram(aes(y=..density..), bins=30) + xlim(97, 103)

# 2. Skewed Population Distribution (Using log-normal as an example)
population2 <- rlnorm(100000, meanlog=4.5, sdlog=0.8)
sample_means2 <- replicate(1000, mean(sample(population2, size=30)))

p3 <- ggplot(data.frame(x=population2), aes(x)) + geom_density() + xlim(0, 300)
p4 <- ggplot(data.frame(x=sample_means2), aes(x)) + geom_histogram(aes(y=..density..), bins=30) + xlim(50, 150)

# 3. Exponential Population Distribution
population3 <- rexp(100000, rate=0.01)
sample_means3 <- replicate(1000, mean(sample(population3, size=30)))

p5 <- ggplot(data.frame(x=population3), aes(x)) + geom_density() + xlim(0, 500)
p6 <- ggplot(data.frame(x=sample_means3), aes(x)) + geom_histogram(aes(y=..density..), bins=30) + xlim(0, 600)

# Display plots
p1
p2
p3
p4
p5
p6
```


```{r}
unit1 = c(10, 10, 10, 50, 30, 40, 50, 40, 30 ,50)
unit2 = c(20, 30, 40, 10, 20, 20, 20, 30, 50, 40)

results <- ((unit1 + unit2) / 2) %>% print()

# 결과를 데이터 프레임으로 변환
df <- data.frame(Sample.Mean = results)
df

# 도트 플롯으로 시각화하기
ggplot(df, aes(x = Sample.Mean)) + 
  geom_dotplot(binwidth = 0.5, stackdir = "center", color=sbl, fill= sbl) +
  labs(title="모평균과 표본 평균(n = 2)", x="표본 평균", y="빈도") +
  ylim(0, 1) +
  theme_bw() + 
  geom_vline(xintercept=30, linetype="dashed", color = "brown")
```
```{r}
# x 축을 위한 데이터 벡터 생성
x <- seq(80, 120, by = 0.1)

# 정규 분포의 확률밀도함수 계산
y <- dnorm(x, mean = 100, sd = 5)

# 데이터 프레임 생성
df <- data.frame(x, y)

y <- replicate(1000, mean(rnorm(30, mean = 100, sd = 5)))

# 그래프 그리기
g1 <- ggplot(df, aes(x = x, y = y)) +
    geom_line() +
    ggtitle("Normal Distribution PDF") +
    xlab("x") +
    ylab("Density") +
    theme_test()

g2 <- ggplot(data.frame(y), aes(y)) +
  geom_histogram(bins=30, fill=sbl, color='black') +
  theme_bw()

# 두 개의 그래프 배열하여 출력
grid.arrange(g1, g2,nrow=1)
```
7page 나머지는 감마분포?


```{r}

```

  
```{r}
# x 값 범위와 확률밀도함수 계산
x <- seq(0, 300, by = 1)
lambda <- 1 / 20
y <- lambda * exp(-lambda * x)

# 데이터 프레임 생성
df <- data.frame(x, y)
df

z <- replicate(1000, mean(rnorm(30, mean = 100, sd = 5)))

# 그래프 생성
ggplot(df, aes(x = x, y = y)) +
  geom_line() +
  ggtitle("Exponential Distribution PDF with Mean 200") +
  xlab("x") +
  ylab("Density") +
  coord_cartesian(xlim = c(0, 300), ylim = c(0, 0.025))
```


```{r}
# 파라미터 설정
lambda <- 1 / 20  # 지수 분포 파라미터
n <- 30  # 표본 크기
reps <- 1000  # 반복 횟수

# 표본평균을 저장할 빈 벡터 초기화
sample_means <- numeric(reps)

# 1,000번 반복하여 표본평균 계산
for (i in 1:reps) {
  sample <- rexp(n, rate = lambda)  # 지수 분포에서 n개의 표본 추출
  sample_means[i] <- mean(sample)  # 표본평균 계산
}

# 결과를 데이터 프레임으로 변환
df <- data.frame(Sample.Mean = sample_means)

# 히스토그램 그리기
ggplot(df, aes(x = Sample.Mean)) +
  geom_histogram(binwidth = 5, fill = sbl, alpha = 0.7) +
  ggtitle("Histogram of Sample Means (n = 30)") +
  xlab("Sample Mean") +
  ylab("Frequency")
```



```{r}
# 초기 설정
num_samples <- 30  # 표본의 크기
num_reps <- 1000  # 반복 횟수

# 빈 벡터를 생성하여 결과를 저장
results_rnorm <- numeric(num_reps)
results_runif <- numeric(num_reps)
results_rchisq <- numeric(num_reps)

# 1000번 반복
for (i in 1:num_reps) {
  # n=30의 표본을 정규분포에서 추출
  sample_rnorm <- rnorm(num_samples, mean=100, sd=10)
  #dnorm(sample_rnorm, mean = 100, sd = 5)
  sample_runif <- runif(num_samples, min = 0, max = 100)
  sample_rchisq <- rchisq(num_samples, 10)  # 자유도(df)가 10
  
  # 계산한 통계량을 results 벡터에 저장 (예: 표본 평균)
  results_rnorm[i] <- mean(sample_rnorm)
  results_runif[i] <- mean(sample_runif)
  results_rchisq[i] <- mean(sample_rchisq)
}
# 결과를 확인
hist(results_rnorm)
hist(results_runif)
hist(results_rchisq)
```


# page15 자유도에 따른 카이제곱분포의 형태
```{r}
# x 축을 위한 데이터 벡터 생성 (0부터 30까지)
x <- seq(0, 30, by = 0.1)

# 자유도가 1, 2, 3, 5, 10인 카이제곱 분포의 확률밀도함수 계산
y_df1 <- dchisq(x, df = 1)
y_df2 <- dchisq(x, df = 2)
y_df3 <- dchisq(x, df = 3)
y_df5 <- dchisq(x, df = 5)
y_df10 <- dchisq(x, df = 10)

# 데이터 프레임 생성
df <- data.frame(x, y_df1, y_df2, y_df3, y_df5, y_df10)

# 그래프 그리기
ggplot(df, aes(x = x)) +
  geom_line(aes(y = y_df1, color = 'df = 4')) +
  geom_line(aes(y = y_df2, color = 'df = 14')) +
  geom_line(aes(y = y_df3, color = 'df = 29')) +
  geom_line(aes(y = y_df5, color = 'df = 39')) +
  geom_line(aes(y = y_df10, color = 'df = 49')) +
  ggtitle("Chi-Squared Distributions with Different Degrees of Freedom") +
  xlab("x") +
  ylab("Density") +
  scale_color_manual(values = c('red', 'blue', 'green', 'purple', 'orange')) +
  theme_minimal()
```



데이터 불러오기
```{r}
test <- read.csv(paste0(data_path, "recognition.test.csv"))
str(test)
```
결함율 계산 및 시각화
```{r}
test <- test %>% 
  mutate(id = fct_reorder(id, mean),
         success_p = ppois(2, mean)) %>% 
  print()
```
```{r}
test %>% ggplot(aes(x = fct_reorder(id, -mean),
                    y = mean)) +
  geom_bar(stat = "identity",
           color = "white", fill = lre) +
  labs(x = "인식 대상", y = "결점 평균") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.y = element_text(size = 5))
```
```{r}
test %>% ggplot(aes(x = fct_reorder(id, success_p),
                    y = success_p)) +
  geom_bar(stat = "identity",
           color = "white", fill = sbl) +
  geom_hline(yintercept = 0.05, color = lre) +
  geom_hline(yintercept = 0.10, color = lre) +
  labs(x = "인식 대상", y = "조건 만족 확률") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.y = element_text(size = 5))
```





